In [6]:
import numpy as np
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
sum=np.add(arr1,arr2)
diff=np.subtract(arr1,arr2)
pro=np.multiply(arr1,arr2)
div=np.divide(arr1,arr2)
print(sum)

[[12 14 16]
 [18 20 22]
 [24 26 28]]


In [7]:
print(diff)

[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]


In [8]:
print(pro)

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [9]:
print(div)

[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]


In [10]:
import numpy as np
arr1=np.arange(1,19).reshape(2,3,3)
print(arr1)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [11]:
arr1[1:]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [12]:
arr1[0:1]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [13]:
arr1[0:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
arr1[1,0:2,2]

array([12, 15])

In [16]:
arr1[-1::]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [17]:
arr1[1:-1]

array([], shape=(0, 3, 3), dtype=int32)

In [19]:
arr1[-1::-1]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]])

In [20]:
arr1[1,1:2,1]

array([14])

In [23]:
import numpy as np
arr=np.arange(1,10).reshape(3,3)
print(arr)
a=arr+10
b=np.sqrt(arr)
c=np.exp(arr)
d=arr*2
e=np.sin(arr)
f=np.cos(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [24]:
print(a)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [25]:
print(b)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [26]:
print(c)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [27]:
print(d)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [28]:
print(e)

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [29]:
print(f)

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [31]:
import numpy as np
arr=np.arange(1,17).reshape(4,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [32]:
np.mean(arr)

8.5

In [33]:
np.std(arr)

4.6097722286464435

In [34]:
np.var(arr)

21.25

In [35]:
np.percentile(arr,2)

1.3

In [36]:
np.min(arr)

1

In [37]:
np.max(arr)

16

In [38]:
np.cumsum(arr)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136], dtype=int32)

In [39]:
np.cumproduct(arr)

array([         1,          2,          6,         24,        120,
              720,       5040,      40320,     362880,    3628800,
         39916800,  479001600, 1932053504, 1278945280, 2004310016,
       2004189184], dtype=int32)

In [43]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
a=list(arr1)+list(arr2)
print(a)
b=set(a)
print(b)

[1, 2, 3, 4, 5, 6]
{1, 2, 3, 4, 5, 6}


In [44]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
a=np.union1d(arr1,arr2)
print(a)

[1 2 3 4 5 6]


In [45]:
b=np.intersect1d(arr1,arr2)
b

array([], dtype=int32)

In [47]:
c=np.unique(arr1)
c

array([1, 2, 3])

In [49]:
d=np.setxor1d(arr1,arr2)
d

array([1, 2, 3, 4, 5, 6])